# docker-compose.yml
version: '3'

services:
  backend:
    build: ./mental-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=your_mongodb_uri
      - JWT_SECRET=>h]k~WAz&b?Sdjt,Y9@
  
  frontend:
    build: ./mental-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
